# Generated by Django 5.0.3 on 2025-01-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=191)),
                ('description', models.TextField(default='', max_length=191)),
                ('recommended_retail_price', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(default='', max_length=191)),
                ('photo', models.ImageField(default='', upload_to='photos/%Y/%m/&d')),
                ('category', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BranchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant_name', models.CharField(blank=True, max_length=191, null=True)),
                ('merchant_logo', models.CharField(blank=True, max_length=191, null=True)),
                ('branch_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('store_reference', models.CharField(default='', max_length=191)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.globalproduct')),
            ],
        ),
    ]
