# Generated by Django 5.0.3 on 2025-02-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchproduct',
            name='merchant_logo',
        ),
        migrations.RemoveField(
            model_name='branchproduct',
            name='merchant_name',
        ),
    ]
