# Generated by Django 5.0.3 on 2025-03-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_branchproduct_merchant_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchproduct',
            old_name='product',
            new_name='global_product',
        ),
    ]
