# Generated by Django 5.0.3 on 2025-04-06 12:02

import apps.orders.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('CUSTOMER_REQUEST', 'Customer Requested'), ('OUT_OF_STOCK', 'Items Out of Stock'), ('DELIVERY_ISSUES', 'Delivery Issues'), ('PAYMENT_FAILED', 'Payment Failed'), ('OTHER', 'Other')], max_length=50)),
                ('additional_notes', models.TextField(blank=True)),
                ('refund_initiated', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.useraccount')),
            ],
            options={
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_DELIVERY', 'PENDING_DELIVERY'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('PENDING_PICKUP', 'PENDING_PICKUP'), ('PAYMENT_PENDING', 'PAYMENT_PENDING')], default='PAYMENT_PENDING', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledgement_notification_sent', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('delivery_date', models.CharField(default=apps.orders.models.setDate, max_length=100, null=True)),
                ('delivery_address', models.CharField(max_length=191, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.useraccount')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
    ]
