# Generated by Django 5.0.3 on 2025-01-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0002_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
    ]
