# Generated by Django 5.0.3 on 2025-01-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_alter_salecampaign_campaign_ends'),
        ('orders', '0003_order_delivery_fee'),
        ('products', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
    ]
