# Generated by Django 5.0.3 on 2025-03-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cancelledorder_order_order_ordered_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliveryDate',
            new_name='delivery_date',
        ),
    ]
