# Generated by Django 5.0.3 on 2025-03-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_can_create_merchants_useraccount_is_super_user'),
        ('orders', '0007_rename_address_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.useraccount'),
        ),
    ]
