# Generated by Django 5.0.3 on 2025-03-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_products',
            new_name='products_ordered',
        ),
    ]
