# Generated by Django 5.0.3 on 2025-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_ordered_products_order_products_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acknowledgement_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
