# Generated by Django 5.1.7 on 2025-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_acknowledgement_notification_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_DELIVERY', 'PENDING_DELIVERY'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('PENDING_PICKUP', 'PENDING_PICKUP'), ('PAYMENT_PENDING', 'PAYMENT_PENDING')], default='PAYMENT_PENDING', max_length=16),
        ),
    ]
