# Generated by Django 5.1.7 on 2025-03-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelledorder',
            old_name='refund_initiated',
            new_name='refunded',
        ),
        migrations.AddField(
            model_name='cancelledorder',
            name='refund_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
