# Generated by Django 5.1.7 on 2025-04-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_refund_initiated_cancelledorder_refunded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelledorder',
            old_name='refunded',
            new_name='refund_initiated',
        ),
        migrations.RemoveField(
            model_name='cancelledorder',
            name='refund_date',
        ),
    ]
