# Generated by Django 5.1.7 on 2025-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_refunded_cancelledorder_refund_initiated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelledorder',
            old_name='refund_initiated',
            new_name='refunded',
        ),
        migrations.AddField(
            model_name='cancelledorder',
            name='refund_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
