# Generated by Django 5.0.3 on 2025-01-13 13:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=120, null=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('paygate_reference', models.CharField(default='', max_length=120)),
                ('paygate_id', models.CharField(max_length=20, unique=True)),
                ('paygate_secret', models.CharField(max_length=32, null=True)),
                ('fernet_token', models.CharField(blank=True, max_length=120, unique=True)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=120)),
                ('area', models.CharField(default='', max_length=120)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchantbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='SaleCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('percentage_off', models.PositiveIntegerField()),
                ('campaign_ends', models.DateField(default=datetime.datetime(2025, 1, 13, 15, 3, 18, 219551))),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.branch')),
            ],
        ),
    ]
