# Generated by Django 5.0.3 on 2025-04-06 12:02

import apps.merchants.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=120, null=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('closing_time', models.TimeField(default=datetime.time(16, 30))),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
            options={
                'verbose_name': 'a business',
                'verbose_name_plural': 'My Business',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=120)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchantbusiness')),
            ],
            options={
                'verbose_name': 'a branch',
                'verbose_name_plural': 'My Branches',
            },
        ),
        migrations.CreateModel(
            name='SaleCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('percentage_off', models.PositiveIntegerField()),
                ('campaign_ends', models.DateField(default=apps.merchants.models.default_campaign_end_date)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.branch')),
            ],
            options={
                'verbose_name': 'Sale Campaign',
                'verbose_name_plural': 'Sale Campaigns',
            },
        ),
    ]
