# Generated by Django 5.0.3 on 2025-01-13 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecampaign',
            name='campaign_ends',
            field=models.DateField(default=datetime.datetime(2025, 1, 18, 15, 7, 1, 437076)),
        ),
    ]
