# Generated by Django 5.0.3 on 2025-01-16 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_alter_merchantbusiness_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecampaign',
            name='campaign_ends',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 13, 21, 1, 201569)),
        ),
    ]
