# Generated by Django 5.0.3 on 2025-01-16 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_alter_salecampaign_campaign_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantbusiness',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='salecampaign',
            name='campaign_ends',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 13, 27, 48, 478943)),
        ),
    ]
