# Generated by Django 5.0.3 on 2025-01-17 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0012_alter_salecampaign_campaign_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecampaign',
            name='campaign_ends',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 12, 55, 57, 53229)),
        ),
    ]
