# Generated by Django 5.0.3 on 2025-01-31 07:52

import apps.merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0013_alter_salecampaign_campaign_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecampaign',
            name='campaign_ends',
            field=models.DateField(default=apps.merchants.models.default_campaign_end_date),
        ),
    ]
