# Generated by Django 5.0.3 on 2025-02-10 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0014_alter_salecampaign_campaign_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(default=datetime.time(16, 30)),
        ),
    ]
