# Generated by Django 5.0.3 on 2025-02-10 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0015_branch_closing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='closing_time',
        ),
        migrations.AddField(
            model_name='merchantbusiness',
            name='closing_time',
            field=models.TimeField(default=datetime.time(16, 30)),
        ),
    ]
