# Generated by Django 5.0.3 on 2025-02-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0016_remove_branch_closing_time_and_more'),
        ('products', '0002_remove_branchproduct_merchant_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'a branch', 'verbose_name_plural': 'My Branches'},
        ),
        migrations.AlterModelOptions(
            name='merchantbusiness',
            options={'verbose_name': 'a business', 'verbose_name_plural': 'My Business'},
        ),
        migrations.AlterModelOptions(
            name='salecampaign',
            options={'verbose_name': 'Sale Campaign', 'verbose_name_plural': 'Sale Campaigns'},
        ),
        migrations.AlterField(
            model_name='salecampaign',
            name='branch_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.branchproduct', unique=True),
        ),
    ]
