# Generated by Django 5.0.3 on 2025-02-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0017_alter_branch_options_alter_merchantbusiness_options_and_more'),
        ('products', '0002_remove_branchproduct_merchant_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecampaign',
            name='branch_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.branchproduct', unique=True),
        ),
    ]
