# Generated by Django 5.0.3 on 2025-03-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0018_alter_salecampaign_branch_product'),
        ('products', '0002_remove_branchproduct_merchant_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='area',
        ),
        migrations.AlterField(
            model_name='salecampaign',
            name='branch_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.branchproduct'),
        ),
    ]
