# Generated by Django 5.0.3 on 2025-03-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0019_remove_branch_area_alter_salecampaign_branch_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantbusiness',
            name='fernet_token',
        ),
        migrations.RemoveField(
            model_name='merchantbusiness',
            name='paygate_id',
        ),
        migrations.RemoveField(
            model_name='merchantbusiness',
            name='paygate_reference',
        ),
        migrations.RemoveField(
            model_name='merchantbusiness',
            name='paygate_secret',
        ),
    ]
