# Generated by Django 5.1.7 on 2025-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0020_remove_merchantbusiness_fernet_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecampaign',
            name='delayed_percentage_off',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salecampaign',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
