# Generated by Django 5.0.3 on 2025-01-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=191, null=True)),
                ('num_of_orders_placed', models.PositiveBigIntegerField(blank=True, null=True)),
                ('num_of_orders_fulfilled', models.PositiveBigIntegerField(blank=True, null=True)),
                ('num_of_orders_cancelled', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=191)),
                ('phone_number', models.PositiveIntegerField(null=True, unique=True)),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_merchant', models.BooleanField(default=False)),
                ('device_token', models.CharField(max_length=191)),
                ('can_create_merchants', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password_change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
