# Generated by Django 5.0.3 on 2025-02-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='can_create_merchants',
            new_name='is_super_user',
        ),
    ]
