# Generated by Django 5.1.7 on 2025-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_can_create_merchants_useraccount_is_super_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
