# Generated by Django 5.0.3 on 2025-04-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('merchants', '0002_initial'),
        ('orders', '0001_initial'),
        ('paystack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=191, null=True)),
                ('total_with_service_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_minus_service_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('DECLINED', 'Declined'), ('NOT_DONE', 'Not Done'), ('RECEIVED_BY_PAYGATE', 'Received by PayGate'), ('SETTLEMENT_VOIDED', 'Settlement Voided'), ('CUSTOMER_CANCELLED', 'Customer Cancelled')], default='PENDING', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paystack.payment')),
                ('products_ordered', models.ManyToManyField(blank=True, to='orders.orderedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
