# Generated by Django 5.0.3 on 2025-01-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('merchants', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payRequestId', models.CharField(max_length=36, null=True)),
                ('reference', models.CharField(max_length=191, null=True)),
                ('numberOfProducts', models.PositiveIntegerField(default=0)),
                ('amount', models.CharField(default='0.00', max_length=7)),
                ('discountTotal', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateCompleted', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
                ('products_purchased', models.ManyToManyField(blank=True, to='orders.orderedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
