# Generated by Django 5.0.3 on 2025-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amount_minus_service_fee',
        ),
        migrations.AddField(
            model_name='transaction',
            name='full_amount',
            field=models.CharField(default='0.00', max_length=7),
        ),
    ]
