# Generated by Django 5.0.3 on 2025-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_amount_transaction_amount_minus_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
