# Generated by Django 5.0.3 on 2025-02-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('DECLINED', 'Declined'), ('NOT_DONE', 'Not Done'), ('RECEIVED_BY_PAYGATE', 'Received by PayGate'), ('SETTLEMENT_VOIDED', 'Settlement Voided'), ('CUSTOMER_CANCELLED', 'Customer Cancelled')], default='PENDING', max_length=50),
        ),
    ]
