# Generated by Django 5.0.3 on 2025-03-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='dateCreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='dateCompleted',
            new_name='date_completed',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='discountTotal',
            new_name='discount_total',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='full_amount',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='products_purchased',
            new_name='products_ordered',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='numberOfProducts',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payRequestId',
        ),
    ]
