# Generated by Django 5.0.3 on 2025-03-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0001_initial'),
        ('transactions', '0005_rename_datecreated_transaction_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paystack.payment'),
        ),
    ]
