# Generated by Django 5.0.3 on 2025-03-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_minus_service_fee',
            new_name='total_minus_service_fee',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='grand_total',
            new_name='total_with_service_fee',
        ),
    ]
