# Generated by Django 5.0.3 on 2025-03-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_rename_amount_minus_service_fee_transaction_total_minus_service_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_completed',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount_total',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service_fee',
        ),
    ]
