# Generated by Django 5.0.3 on 2025-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_date_completed_transaction_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
