# Generated by Django 5.0.3 on 2025-03-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_paystack_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paystack_reference',
        ),
    ]
