# Generated by Django 5.0.3 on 2025-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_remove_transaction_paystack_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_minus_service_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_with_service_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
