# Generated by Django 5.0.3 on 2025-02-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0016_remove_branch_closing_time_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('merchant_business', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchantbusiness', unique=True)),
                ('transactions', models.ManyToManyField(blank=True, to='transactions.transaction')),
            ],
        ),
    ]
