# Generated by Django 5.0.3 on 2025-02-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_wallets', '0001_initial'),
        ('merchants', '0016_remove_branch_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantwallet',
            name='merchant_business',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchantbusiness'),
        ),
    ]
